
name: "Task Issue Parser"
description: "Add task to registry or add a bug"
author: ""
inputs:
  GITHUB_TOKEN:
    description: "set secrets.GITHUB_TOKEN here"
outputs:
  change_types:
    description: 'string containign types of changes in PR'

runs:
  using: "node12"
  main: "dist/index.js"
