name: Add New Task

on:
  issues: {types: opened}

jobs:
  comment:
    if: github.event.label.name == 'data request'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Parse Task Issue
      id: issue_parser
      uses: brown-ccv/gh-actions/parse-task-issue@parse-task-issue
      with:
<<<<<<< Updated upstream
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
=======
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Issue Commenter on success
      if: ${{ success() }}
      uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "We have started a PR for this issue"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Issue Commenter on failure
      if: ${{ failure() }}
      uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "This issue has failed"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  pr-creation:
    if: contains(github.event.issue.labels.*.name, 'data request')
    runs-on: ubuntu-latest

    needs: issue-jobs
    steps:
    - uses: actions/checkout@v2
    - name: Create file
      working-directory: ./data
      run: echo "${{env.FILE_DATA}}" > ${{env.FILE_NAME}}
      env:
        FILE_NAME: ${{needs.issue-jobs.outputs.file_name}}
        FILE_DATA: ${{needs.issue-jobs.outputs.file_content}}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
    - name: Issue Commenter on success
      if: ${{ success() }}
      uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "We have created a PR for this issue"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Issue Commenter on failure
      if: ${{ failure() }}
      uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "PR creation failed"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

>>>>>>> Stashed changes
