name: Add New Task

on:
  issues:
    types: [opened, reopened, labeled, edited]

jobs:
  build:
    if: contains(github.event.issue.labels.*.name, 'data request')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
  issue-jobs:
    if: contains(github.event.issue.labels.*.name, 'data request')
    runs-on: ubuntu-latest
    needs: build  
    steps:
    - name: Parse Task Issue
      id: issue_parser
      uses: brown-ccv/gh-actions/parse-task-issue@parse-task-issue
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Issue Commenter on success
      if: ${{ success() }}
      uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "We have started a PR for this issue"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Issue Commenter on failure
      if: ${{ failure() }}
      uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "This issue has failed"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Check the output from issue parser
      if: ${{ success() }}
      run: echo "${{steps.issue_parser.outputs.file_name}}"
    # - name: Create file
    #   if: ${{ success() }}
    #   uses: finnp/create-file-action@master
    #   env:
    #     FILE_NAME: ${{steps.issue_parser.outputs.file_name}}
    #     FILE_DATA: ${{steps.issue_parser.outputs.file_content}}
    
