name: Add New Task

on:
  issues:
    types: [opened, reopened, labeled, edited]

jobs:
  comment:
    if: contains(github.event.issue.labels.*.name, 'data request')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Parse Task Issue
      id: issue_parser
      uses: brown-ccv/gh-actions/parse-task-issue@parse-task-issue
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}