name: Add New Task

on:
  pull_request:
    branches:
      - master

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Parse Task Issue
      uses: ./ 
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}